### ISSUE TITLE
Implement CI with Azure Pipelines and GitHub Actions

### ISSUE THREAD

**Issue by gkarwchan** [gkarwchan/propertymanagementportal#12]
https://learn.microsoft.com/en-us/training/paths/az-400-implement-ci-azure-pipelines-github-actions/

## Todo

- [ ] Explore Azure Pipelines
- [ ]  Manage Azure Pipeline agents and pools
- [ ] Describe pipelines and concurrency
- [ ] Design and implement a pipeline strategy
- [ ] Integrate with Azure Pipelines
- [ ] Introduction to GitHub Actions
- [ ] Learn CI with GitHub Actions
- [ ] Design a container build strategy
